#!/usr/bin/env python

import re
import sys

s = open(sys.argv[1], 'r').read()
r = r"\[\d]\s[a-zA-Z]+"
if re.match(r, s) is not None:
    print ("Commit is fine")
    sys.exit(-1)
else:
    print("Commit not fine")
    print('Try this option:[1] initial commit')
    sys.exit(-1)
